language: node_js # 设置语言
node_js: stable # 设置相应版本

# cache:
#     apt: true
#     directories:
#         - node_modules # 缓存不经常更改的内容

notifications:
    email:
        recipients:
            - happyshark520@outlook.com
        on_success: change
        on_failure: always

before_install:
    - export TZ='Asia/Shanghai'
    - npm install hexo-cli -g
    - npm install cheerio
    - chmod +x ./publish-to-gh-pages.sh

install:
    - npm install
    - npm i -g yuque-hexo
    - npm install hexo-deployer-git --save

script:
    - yuque-hexo clean
    - yuque-hexo sync
    - npm run sync
    - hexo clean
    - hexo g

after_script:
    - ./publish-to-gh-pages.sh

branches:
    only:
        - master #只监测hexo分支，hexo是我的分支的名称，可根据自己情况设置
env:
    global:
        - GH_REF: github.com/HPShark/HPShark.github.io.git #设置GH_REF，注意更改yourname
